namespace GorillaShirts.Models.UI
{
    public enum EButtonType
    {
        NavigateSelect,
        NavigateIncrease,
        NavigateDecrease,
        Return,
        Info,
        RigToggle,
        Capture,
        Randomize,
        TagIncrease,
        TagDecrease,
        Button1,
        Button2,
        Favourite,
        PackBrowser,
        Credits,
        Statistics,
        Tutorial,
        Button3,
        Button4,
        Button5,
        Button6,
        Button7,
        Button8,
        Button9,
        Button10
    }
}
